version: "3.9"

services:
  core:
    image: ghcr.io/defguard/defguard:latest
    env_file:
      - .env
    ports:
      # REST API
      - "8000:8000"
      # gRPC
      - "50055:50055"
    depends_on:
      - gateway
    volumes:
      - /etc/wireguard:/etc/wireguard

  gateway:
    image: ghcr.io/defguard/gateway:latest
    environment:
      DEFGUARD_GRPC_URL: http://core:50055
      DEFGUARD_STATS_PERIOD: 60
      DEFGUARD_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJEZWZHdWFyZCIsInN1YiI6IlRlc3ROZXQiLCJjbGllbnRfaWQiOiIiLCJleHAiOjU5NjE3NDcwNzYsIm5iZiI6MTY2Njc3OTc4MSwicm9sZXMiOltdfQ.uEUMnw_gO23W0K2q3N1lToeP0D2zAY1swr8N-84sRHA
      RUST_LOG: debug
    ports:
      # WireGuard gRPC
      - "50051:50051/udp"
    depends_on:
      - core
    cap_add:
      - NET_ADMIN

  device:
    build:
      context: .
      dockerfile: Dockerfile.device
    depends_on:
      - gateway
    cap_add:
      - NET_ADMIN

  vector:
    image: timberio/vector:latest-alpine
    profiles:
      - observability
    container_name: vector
    volumes:
      - ./configs/vector.yaml:/etc/vector/vector.yaml:ro
      - ./configs/key.pem:/etc/vector/key.pem:ro
      - ./configs/cert.pem:/etc/vector/cert.pem:ro
    command: ["--config", "/etc/vector/vector.yaml"]
    ports:
      - "8686:8686"
      - "8001:8001"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.0
    profiles:
      - observability
    ports:
      - "8002:8002"
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
